pipeline:
    name: deploy
    identifier: deploy
    projectIdentifier: DocGitExp
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: cd-template
              identifier: cdtemplate
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              manifestOverrideSets: []
                              manifests: []
                              artifacts:
                                  sidecars: []
                      serviceRef: <+input>
                  infrastructure:
                      environmentRef: <+input>
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: <+input>
                              namespace: <+input>
                              releaseName: <+input>
                      allowSimultaneousDeployments: false
                      infrastructureKey: <+input>
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
