pipeline:
    name: HelloWorld
    identifier: HelloWorld
    projectIdentifier: DocGitExp
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: HelloWorld
                build: <+input>
    stages:
        - stage:
              name: HelloWorld
              identifier: HelloWorld
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: mvn build
                                identifier: mvn_build
                                spec:
                                    connectorRef: doctestdockerhub
                                    image: maven:3.8.1-openjdk-17
                                    command: mvn clean package
                                    privileged: false
                  serviceDependencies: []
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.DevX_DONOTDELETE
                          namespace: default
